block.4 = short_grass tall_grass large_fern fern white_tulip red_tulip cobweb pink_tulip orange_tulip seagrass rose_bush peony dandelion cornflower blue_orchid lily_pad spruce_leaves oak_leaves \
              tall_seagrass lilac sweet_berry_bush dead_bush big_dripleaf big_dripleaf_stem sugar_cane small_dripleaf poppy cherry_sapling sunflower allium vine wheat carrots potatoes beetroots \
              azure_bluet wildflowers dark_oak_sapling acacia_sapling oak_sapling spruce_sapling birch_sapling jungle_sapling flowering_azalea azalea lily_of_the_valley kelp_plant oxeye_daisy \
              wither_rose bush pink_petals tall_dry_grass short_dry_grass cherry_leaves birch_leaves acacia_leaves jungle_leaves dark_oak_leaves mangrove_leaves azalea_leaves flowering_azalea_leaves \
              target cactus snow snow_block \
              yellow_wool yellow_carpet white_wool white_carpet red_wool red_carpet blue_wool blue_carpet \
              lime_wool lime_carpet purple_wool purple_carpet magenta_wool magenta_carpet pink_wool pink_carpet \
              black_wool black_carpet light_gray_wool light_gray_carpet gray_wool gray_carpet brown_wool brown_carpet \
              green_wool green_carpet cyan_wool cyan_carpet light_blue_wool light_blue_carpet orange_wool orange_carpet 

block.32 = sea_lantern
block.33 = glowstone ochre_froglight
block.34 = redstone_block redstone_torch redstone_wall_torch
block.35 = torch wall_torch campfire lantern 
block.36 = shroomlight lava flowing_lava
block.37 = soul_torch soul_wall_torch soul_lantern soul_campfire
block.38 = copper_torch copper_wall_torch copper_lantern waxed_copper_lantern verdant_froglight
block.39 = exposed_copper_lantern waxed_exposed_copper_lantern
block.40 = weathered_copper_lantern waxed_weathered_copper_lantern
block.41 = oxidized_copper_lantern waxed_oxidized_copper_lantern
block.42 = pearlescent_froglight