#------# Subtle SSS #---------------------------#

block.10001 = target cactus suspicious_sand sand sandstone sandstone_stairs sandstone_slab sandstone_wall chiseled_sandstone smooth_sandstone \
              smooth_sandstone_stairs smooth_sandstone_slab cut_sandstone cut_sandstone_slab red_sand red_sandstone red_sandstone_stairs \
              red_sandstone_slab red_sandstone_wall red_chiseled_sandstone red_smooth_sandstone red_smooth_sandstone_stairs lapis_block \
              red_smooth_sandstone_slab red_cut_sandstone red_cut_sandstone_slab pumpkin carved_pumpkin blue_ice cake firefly_bush \
              packed_mud mud_bricks mud_brick_stairs mud_brick_slab mud_brick_wall jack_o_lantern melon scaffolding spore_blossom torchflower \
              brown_mushroom red_mushroom honeycomb_block %concrete_powder %candle_cakes %candles %flower_pots %snow 

#------# Medium SSS #---------------------------#

block.10002 = short_grass tall_grass large_fern fern white_tulip red_tulip cobweb pink_tulip orange_tulip seagrass rose_bush peony \
              dandelion cornflower blue_orchid lily_pad tall_seagrass lilac sweet_berry_bush dead_bush big_dripleaf big_dripleaf_stem \
              sugar_cane small_dripleaf poppy cherry_sapling sunflower allium vine wheat carrots potatoes beetroots azure_bluet wildflowers \
              dark_oak_sapling acacia_sapling oak_sapling spruce_sapling birch_sapling jungle_sapling lily_of_the_valley kelp_plant \
              oxeye_daisy wither_rose bush pink_petals tall_dry_grass short_dry_grass hay_block packed_ice pale_moss_block moss_block \
              pale_moss_carpet moss_carpet mud brown_mushroom_block red_mushroom_block mushroom_stem %wool %wool_carpets 

#------# Strong SSS #---------------------------#

block.10003 = flowering_azalea azalea %leaves

#------# Metallic blocks #----------------------#

block.10004 = iron_block gold_block copper_block exposed_copper iron_door iron_trapdoor iron_bars

#------# Light tinting blocks #-----------------#

block.10016 = white_stained_glass glass
block.10017 = orange_stained_glass
block.10018 = magenta_stained_glass
block.10019 = light_blue_stained_glass
block.10020 = yellow_stained_glass
block.10021 = lime_stained_glass
block.10022 = pink_stained_glass
block.10023 = gray_stained_glass
block.10024 = light_gray_stained_glass
block.10025 = cyan_stained_glass
block.10026 = purple_stained_glass
block.10027 = blue_stained_glass
block.10028 = brown_stained_glass
block.10029 = green_stained_glass
block.10030 = red_stained_glass
block.10031 = black_stained_glass tinted_glass

#------# Light emitting blocks #----------------#

block.10032 = sea_lantern
block.10033 = glowstone ochre_froglight redstone_lamp:lit=true
block.10034 = redstone_block redstone_torch:lit=true redstone_wall_torch:lit=true
block.10035 = torch wall_torch campfire:lit=true lantern 
block.10036 = shroomlight lava flowing_lava fire cave_vines:berries=true cave_vines_plant:berries=true
block.10037 = soul_torch soul_wall_torch soul_lantern soul_campfire:lit=true soul_fire
block.10038 = copper_torch copper_wall_torch copper_lantern waxed_copper_lantern verdant_froglight
block.10039 = exposed_copper_lantern waxed_exposed_copper_lantern
block.10040 = weathered_copper_lantern waxed_weathered_copper_lantern
block.10041 = oxidized_copper_lantern waxed_oxidized_copper_lantern
block.10042 = pearlescent_froglight
block.10043 = end_rod
block.10044 = crying_obsidian
block.10045 = magma_block

layer.solid = nether_portal
layer.translucent = glass glass_pane