
#define BLOCK_WATER 254
#define BLOCK_UNDEFINED 255

/*

#------# Subtle SSS #---------------------------#

block.1 = target suspicious_sand sand sandstone sandstone_wall chiseled_sandstone smooth_sandstone \
          cut_sandstone red_sand red_sandstone \
          red_sandstone_wall red_chiseled_sandstone red_smooth_sandstone crimson_roots bamboo \
          red_cut_sandstone pumpkin carved_pumpkin blue_ice cake firefly_bush pitcher_crop \
          packed_mud mud_bricks mud_brick_wall melon scaffolding spore_blossom nether_wart warped_roots \
          brown_mushroom red_mushroom honeycomb_block sponge wet_sponge %concrete_powder %candle_cakes %candles:lit=false snow_block

#------# Medium SSS #---------------------------#

block.2 = short_grass tall_grass large_fern fern cobweb seagrass lily_pad tall_seagrass sweet_berry_bush dead_bush big_dripleaf \
          big_dripleaf_stem sugar_cane small_dripleaf vine wheat carrots potatoes beetroots kelp_plant wither_rose bush pink_petals \
          tall_dry_grass short_dry_grass pale_moss_carpet moss_carpet cactus %saplings %flowers

#------# Strong SSS #---------------------------#

block.3 = flowering_azalea azalea %leaves

#------# Metallic non-full blocks #-------------#

block.4 = iron_door iron_trapdoor iron_bars light_weighted_pressure_plate heavy_weighted_pressure_plate

#------# Non-full blocks # ---------------------#

block.5 = %slabs:type=bottom %slabs:type=top %stairs %trapdoors %wool_carpets %buttons %wooden_doors %fence_gates %fences %walls %rails %pressure_plates %flower_pots repeater comparator redstone_wire ladder snow sea_pickle leaf_litter lever redstone_torch:lit=false redstone_wall_torch:lit=false tripwire_hook

#------# Metallic full blocks # ----------------#

block.6 = iron_block gold_block copper_block exposed_copper 

# ----- Medium SSS full blocks -----

block.7 = hay_block packed_ice pale_moss_block moss_block mud brown_mushroom_block red_mushroom_block mushroom_stem dried_kelp_block %wool

#------# Light tinting blocks #-----------------#

block.16 = white_stained_glass glass
block.17 = orange_stained_glass honey_block 
block.18 = magenta_stained_glass
block.19 = light_blue_stained_glass ice
block.20 = yellow_stained_glass
block.21 = lime_stained_glass slime_block
block.22 = pink_stained_glass
block.23 = gray_stained_glass
block.24 = light_gray_stained_glass
block.25 = cyan_stained_glass
block.26 = purple_stained_glass
block.27 = blue_stained_glass
block.28 = brown_stained_glass
block.29 = green_stained_glass
block.30 = red_stained_glass
block.31 = black_stained_glass tinted_glass

#------# Light emitting blocks #----------------#

block.32 = sea_lantern
block.33 = glowstone ochre_froglight redstone_lamp:lit=true conduit
block.34 = redstone_block redstone_torch:lit=true redstone_wall_torch:lit=true redstone_ore:lit=true deepslate_redstone_ore:lit=true
block.35 = torch wall_torch campfire:lit=true lantern 
block.36 = shroomlight lava flowing_lava lava_cauldron fire cave_vines:berries=true cave_vines_plant:berries=true
block.37 = soul_torch soul_wall_torch soul_lantern soul_campfire:lit=true soul_fire
block.38 = copper_torch copper_wall_torch copper_lantern waxed_copper_lantern verdant_froglight
block.39 = exposed_copper_lantern waxed_exposed_copper_lantern
block.40 = weathered_copper_lantern waxed_weathered_copper_lantern
block.41 = oxidized_copper_lantern waxed_oxidized_copper_lantern
block.42 = pearlescent_froglight
block.43 = end_rod
block.44 = crying_obsidian
block.45 = magma_block
block.46 = copper_bulb:lit=true waxed_copper_bulb:lit=true jack_o_lantern
block.47 = exposed_copper_bulb:lit=true waxed_exposed_copper_bulb:lit=true creaking_heart:creaking_heart_state=awake furnace:lit=true blast_furnace:lit=true smoker:lit=true
block.48 = weathered_copper_bulb:lit=true waxed_weathered_copper_bulb:lit=true creaking_heart:creaking_heart_state=dormant torchflower
block.49 = oxidized_copper_bulb:lit=true waxed_oxidized_copper_bulb:lit=true %candles:lit=true open_eyeblossom
block.50 = glow_lichen
block.51 = amethyst_cluster
block.52 = large_amethyst_bud
block.53 = medium_amethyst_bud
block.54 = small_amethyst_bud
block.55 = brewing_stand
block.56 = beacon
block.57 = nether_portal

block.254 = water flowing_water

layer.solid = nether_portal
layer.translucent = glass glass_pane

*/