
# -----

iris.features.required = SEPARATE_HARDWARE_SAMPLERS CUSTOM_IMAGES SSBO

oldLighting = false

shadow.culling = reversed

# ----- Options Menu -----

profile.default = TEMPORAL_UPSAMPLING=1 CLOUDS_VIEW_SCATTER_POINTS=32 shadowDistance=192 SHADOW_SAMPLES=8
profile.performance = TEMPORAL_UPSAMPLING=2 CLOUDS_VIEW_SCATTER_POINTS=20 shadowDistance=128 SHADOW_SAMPLES=6

screen.columns = 2
screen = [zephyr_shaders] <profile> <empty> <empty> [lighting] [shadows] [atmospherics] [surface] [anti_aliasing] [post_processing] [misc] [debug]

screen.zephyr_shaders.columns = 1
screen.zephyr_shaders = ENABLE_TEXT_RENDERING

screen.lighting.columns = 2
screen.lighting = NIGHT_BRIGHTNESS [indirect_lighting] <empty> <empty> COLORED_LIGHTING VOXEL_DISTANCE

    screen.indirect_lighting.columns = 1
    screen.indirect_lighting = GTAO_RADIUS GTAO_SLICES GTAO_HORIZON_STEPS <empty> SUNLIGHT_GI_SAMPLES SUNLIGHT_GI_RANGE

screen.shadows.columns = 2
screen.shadows = shadowMapResolution shadowDistance SHADOW_SOFTNESS SHADOW_SAMPLES

screen.atmospherics.columns = 2
screen.atmospherics = VOLUMETRIC_CLOUDS CLOUDS_SCALE CLOUDS_VIEW_SCATTER_POINTS CLOUDS_LIGHT_SCATTER_POINTS <empty> <empty> AIR_FOG_VL AIR_FOG_SCATTER_POINTS 

screen.surface.columns = 2
screen.surface = HARDCODED_SPECULAR EMISSIVE_SCALE SSS_ENABLED SSS_INTENSITY
 
screen.anti_aliasing.columns = 2
screen.anti_aliasing = TAA TEMPORAL_UPSAMPLING <empty> <empty> TAA_HISTORY_LIMIT TAA_DEPTH_REJECTION

screen.post_processing.columns = 2
screen.post_processing = tonemap <empty> PURKINJE_EFFECT PURKINJE_AMOUNT

screen.misc = 
screen.debug = 

sliders = shadowMapResolution shadowDistance SHADOW_SOFTNESS SHADOW_SAMPLES NIGHT_BRIGHTNESS GTAO_RADIUS GTAO_SLICES GTAO_HORIZON_STEPS SUNLIGHT_GI_SAMPLES SUNLIGHT_GI_RANGE PURKINJE_AMOUNT VOXEL_DISTANCE CLOUDS_SCALE CLOUDS_VIEW_SCATTER_POINTS CLOUDS_LIGHT_SCATTER_POINTS AIR_FOG_SCATTER_POINTS EMISSIVE_SCALE SSS_INTENSITY TAA_HISTORY_LIMIT TAA_DEPTH_REJECTION

# ----- Buffer Sizes -----

#if TEMPORAL_UPSAMPLING == 1
    #define taauRenderScale 1.0
#elif TEMPORAL_UPSAMPLING == 2
    #define taauRenderScale 0.7071
#elif TEMPORAL_UPSAMPLING == 3
    #define taauRenderScale 0.5773
#elif TEMPORAL_UPSAMPLING == 4
    #define taauRenderScale 0.5
#endif

size.buffer.colortex2 = taauRenderScale taauRenderScale
size.buffer.colortex3 = taauRenderScale taauRenderScale
size.buffer.colortex7 = taauRenderScale taauRenderScale
size.buffer.colortex12 = taauRenderScale taauRenderScale

size.buffer.colortex5 = 1920 1080

# ----- Blending -----

blend.gbuffers_terrain  = off
blend.gbuffers_entities = off
blend.gbuffers_block    = off
blend.gbuffers_hand     = off
blend.gbuffers_water    = ONE ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA

blend.shadow = off

# ----- Custom Images -----

image.imgSkyIrradiance = skyIrradianceTex rgba rgba8 unsigned_byte false false 8 8

#ifdef COLORED_LIGHTING
    #if VOXEL_DISTANCE == 64
        image.voxelBuffer = voxelSampler red_integer r8ui unsigned_byte true false 128 128 128
        image.lightBuffer = lightSampler rgba rgba8 unsigned_byte false false 128 128 256
    #elif VOXEL_DISTANCE == 128
        image.voxelBuffer = voxelSampler red_integer r8ui unsigned_byte true false 256 256 256
        image.lightBuffer = lightSampler rgba rgba8 unsigned_byte false false 256 256 512
    #elif VOXEL_DISTANCE == 192
        image.voxelBuffer = voxelSampler red_integer r8ui unsigned_byte true false 384 384 384
        image.lightBuffer = lightSampler rgba rgba8 unsigned_byte false false 384 384 768
    #elif VOXEL_DISTANCE == 256
        image.voxelBuffer = voxelSampler red_integer r8ui unsigned_byte true false 512 512 512
        image.lightBuffer = lightSampler rgba rgba8 unsigned_byte false false 512 512 1024
    #endif
#endif

image.noiseimg1 = noisetex1 red r8 unsigned_byte false false 64 64 64

image.lodDepthImg0 = lodDepthTex0 red r32f float false true taauRenderScale taauRenderScale
image.lodDepthImg1 = lodDepthTex1 red r32f float false true taauRenderScale taauRenderScale

# ----- Custom Textures -----

texture.composite.depthtex2 = texture/tonyMcMapface.bin TEXTURE_3D RGBA32F 48 48 48 RGBA FLOAT

customTexture.noisetex0 = texture/noise.png

customTexture.scattering = texture/scattering.png
customTexture.transmittance = texture/transmittance.png

# ----- Shader Storage -----



# ----- Program Toggles -----

#ifndef INDIRECT_LIGHTING
    program.world0/deferred.enabled = false
#endif

#ifndef COLORED_LIGHTING
    program.world0/shadowcomp.enabled = false
#endif

#ifndef VOLUMETRIC_CLOUDS
    program.world0/deferred6.enabled = false
#endif

# ----- Custom Uniforms -----

variable.float.cameraVelocity_x = floor(cameraPositionInt.x - previousCameraPositionInt.x) + (cameraPositionFract.x - previousCameraPositionFract.x)
variable.float.cameraVelocity_y = floor(cameraPositionInt.y - previousCameraPositionInt.y) + (cameraPositionFract.y - previousCameraPositionFract.y)
variable.float.cameraVelocity_z = floor(cameraPositionInt.z - previousCameraPositionInt.z) + (cameraPositionFract.z - previousCameraPositionFract.z)

uniform.vec3.cameraVelocity = vec3(cameraVelocity_x, cameraVelocity_y, cameraVelocity_z)

variable.float.sunDir_x = gbufferModelViewInverse.0.0 * sunPosition.x + gbufferModelViewInverse.1.0 * sunPosition.y + gbufferModelViewInverse.2.0 * sunPosition.z
variable.float.sunDir_y = gbufferModelViewInverse.0.1 * sunPosition.x + gbufferModelViewInverse.1.1 * sunPosition.y + gbufferModelViewInverse.2.1 * sunPosition.z
variable.float.sunDir_z = gbufferModelViewInverse.0.2 * sunPosition.x + gbufferModelViewInverse.1.2 * sunPosition.y + gbufferModelViewInverse.2.2 * sunPosition.z
variable.float.sunDirNorm = 1.0 / sqrt((sunDir_x * sunDir_x) + (sunDir_y * sunDir_y) + (sunDir_z * sunDir_z))

variable.float.sunDirNorm_x = sunDir_x * sunDirNorm
variable.float.sunDirNorm_y = sunDir_y * sunDirNorm
variable.float.sunDirNorm_z = sunDir_z * sunDirNorm

variable.float.moonDir_x = gbufferModelViewInverse.0.0 * moonPosition.x + gbufferModelViewInverse.1.0 * moonPosition.y + gbufferModelViewInverse.2.0 * moonPosition.z
variable.float.moonDir_y = gbufferModelViewInverse.0.1 * moonPosition.x + gbufferModelViewInverse.1.1 * moonPosition.y + gbufferModelViewInverse.2.1 * moonPosition.z
variable.float.moonDir_z = gbufferModelViewInverse.0.2 * moonPosition.x + gbufferModelViewInverse.1.2 * moonPosition.y + gbufferModelViewInverse.2.2 * moonPosition.z
variable.float.moonDirNorm = 1.0 / sqrt((moonDir_x * moonDir_x) + (moonDir_y * moonDir_y) + (moonDir_z * moonDir_z))

variable.float.moonDirNorm_x = moonDir_x * moonDirNorm
variable.float.moonDirNorm_y = moonDir_y * moonDirNorm
variable.float.moonDirNorm_z = moonDir_z * moonDirNorm

uniform.vec3.shadowDir = vec3(if(sunAngle == shadowAngle, sunDirNorm_x, moonDirNorm_x), if(sunAngle == shadowAngle, sunDirNorm_y, moonDirNorm_y), if(sunAngle == shadowAngle, sunDirNorm_z, moonDirNorm_z))
uniform.vec3.moonDir = vec3(moonDirNorm_x, moonDirNorm_y, moonDirNorm_z)
uniform.vec3.sunDir = vec3(sunDirNorm_x, sunDirNorm_y, sunDirNorm_z)

uniform.float.worldAge = ((worldDay % 128) + worldTime / 24000.0) * 1200.0

variable.float.worldAgeDelta = abs(worldAge - smooth(worldAge, 0.1, 0.1))
uniform.float.worldTimeErf = exp(-10.0 * worldAgeDelta)

uniform.float.shadowLightBrightness = if(sunAngle == shadowAngle, 1.0, NIGHT_BRIGHTNESS)

#ifdef VOXY
    variable.float.lodNear = near
    variable.float.lodFar = 32.0 * vxRenderDistance
#else
    variable.float.lodNear = near
    variable.float.lodFar = 4.0 * far
#endif

# Reversed-Z projection matrix

uniform.vec4.gbufferProjScale = vec4(gbufferProjection.0.0, gbufferProjection.1.1, -2.0 * lodNear / (lodFar - lodNear), -2.0 * lodFar * lodNear / (lodFar - lodNear))
uniform.vec4.gbufferProjScaleInv = vec4(gbufferProjectionInverse.0.0, gbufferProjectionInverse.1.1, (lodNear - lodFar) / (2.0 * lodNear * lodFar), 1.0 / lodFar)
uniform.vec4.gbufferProjScalePrev = vec4(gbufferPreviousProjection.0.0, gbufferPreviousProjection.1.1, -2.0 * lodNear / (lodFar - lodNear), -2.0 * lodFar * lodNear / (lodFar - lodNear))
uniform.vec4.gbufferProjScalePrevInv = vec4(1.0 / gbufferPreviousProjection.0.0, 1.0 / gbufferPreviousProjection.1.1, (lodNear - lodFar) / (2.0 * lodNear * lodFar), 1.0 / lodFar)

#ifdef VOXY
    uniform.float.viewDistance = 16.0 * vxRenderDistance
#else
    uniform.float.viewDistance = 2.0 * far
#endif

uniform.vec2.screenSize = vec2(viewWidth, viewHeight)
uniform.vec2.texelSize = vec2(1.0 / viewWidth, 1.0 / viewHeight)

uniform.vec2.internalScreenSize = vec2(taauRenderScale * viewWidth, taauRenderScale * viewHeight)
uniform.vec2.internalTexelSize = vec2(1.0 / internalScreenSize.x, 1.0 / internalScreenSize.y)

variable.float.offsetIndex = floor(0.5 * (frameCounter % 16) + 1.0)
variable.float.offsetIndexPrev = floor(0.5 * ((frameCounter - 1) % 16) + 1.0)

variable.bool.inverse = frameCounter % 2 == 0

uniform.vec2.taa_offset = vec2( \
    if(inverse, -TAA_JITTER_SCALE, TAA_JITTER_SCALE) * internalTexelSize.x * (frac(1.3247179 * offsetIndex + 0.5) * 2.0 - 1.0), \
    if(inverse, -TAA_JITTER_SCALE, TAA_JITTER_SCALE) * internalTexelSize.y * (frac(1.7548776 * offsetIndex + 0.5) * 2.0 - 1.0) \
)

uniform.vec2.taa_offset_prev = vec2( \
    if(inverse, TAA_JITTER_SCALE, -TAA_JITTER_SCALE) * internalTexelSize.x * (frac(1.3247179 * offsetIndexPrev + 0.5) * 2.0 - 1.0), \
    if(inverse, TAA_JITTER_SCALE, -TAA_JITTER_SCALE) * internalTexelSize.y * (frac(1.7548776 * offsetIndexPrev + 0.5) * 2.0 - 1.0) \
)