#-----------------------------------------------#

iris.features.required = SEPARATE_HARDWARE_SAMPLERS CUSTOM_IMAGES SSBO

oldLighting = false

#ifdef COLORED_LIGHTING
    shadow.culling = reversed
#else
    shadow.culling = true
#endif

#------# Options Menu #-------------------------#

screen = shadowMapResolution shadowDistance SHADOW_SOFTNESS SHADOW_SAMPLES NIGHT_BRIGHTNESS TONEMAP_OPERATOR TAA TEMPORAL_UPSAMPLING PURKINJE_EFFECT PURKINJE_AMOUNT COLORED_LIGHTING VOXELIZATION_DISTANCE ENABLE_TEXT_RENDERING

sliders = shadowMapResolution shadowDistance SHADOW_SOFTNESS SHADOW_SAMPLES NIGHT_BRIGHTNESS TEMPORAL_UPSAMPLING PURKINJE_AMOUNT VOXELIZATION_DISTANCE

#------# Buffer Sizes #-------------------------#

#if TEMPORAL_UPSAMPLING == 100
    size.buffer.colortex7 = 1.0 1.0
#elif TEMPORAL_UPSAMPLING == 83
    size.buffer.colortex7 = 0.83 0.83
#elif TEMPORAL_UPSAMPLING == 75
    size.buffer.colortex7 = 0.75 0.75
#elif TEMPORAL_UPSAMPLING == 66
    size.buffer.colortex7 = 0.66 0.66
#elif TEMPORAL_UPSAMPLING == 50
    size.buffer.colortex7 = 0.5 0.5
#elif TEMPORAL_UPSAMPLING == 33
    size.buffer.colortex7 = 0.33 0.33
#elif TEMPORAL_UPSAMPLING == 25
    size.buffer.colortex7 = 0.25 0.25
#endif

#------# Blending #-----------------------------#

blend.gbuffers_terrain  = off
blend.gbuffers_entities = off
blend.gbuffers_block    = off
blend.gbuffers_hand     = off
blend.gbuffers_water    = SRC_ALPHA ONE_MINUS_SRC_ALPHA ONE ONE_MINUS_SRC_ALPHA

#------# Custom Images #------------------------#

image.imgScattering = scattering rgba rgba8 unsigned_byte false false 256 256

#ifdef COLORED_LIGHTING
    #if VOXELIZATION_DISTANCE == 64
        image.voxelBuffer = voxelSampler red_integer r8ui unsigned_byte true false 128 128 128
        image.lightBuffer = lightSampler rgba rgba8 unsigned_byte false false 128 128 256
    #elif VOXELIZATION_DISTANCE == 128
        image.voxelBuffer = voxelSampler red_integer r8ui unsigned_byte true false 256 256 256
        image.lightBuffer = lightSampler rgba rgba8 unsigned_byte false false 256 256 512
    #elif VOXELIZATION_DISTANCE == 192
        image.voxelBuffer = voxelSampler red_integer r8ui unsigned_byte true false 384 384 384
        image.lightBuffer = lightSampler rgba rgba8 unsigned_byte false false 384 384 768
    #elif VOXELIZATION_DISTANCE == 256
        image.voxelBuffer = voxelSampler red_integer r8ui unsigned_byte true false 512 512 512
        image.lightBuffer = lightSampler rgba rgba8 unsigned_byte false false 512 512 1024
    #endif
#endif

#------# Shader Storage #-----------------------#

bufferObject.0 = 4

#------# Program Toggles #----------------------#

program.world0/deferred1.enabled = true

#------# Custom Textures #----------------------#

# https://discordapp.com/channels/237199950235041794/525510804494221312/1416364500591837216

texture.composite.noisetex = texture/stbn.bin TEXTURE_3D RGB8 128 128 64 RGB UNSIGNED_BYTE
texture.deferred.noisetex  = texture/stbn.bin TEXTURE_3D RGB8 128 128 64 RGB UNSIGNED_BYTE
texture.gbuffers.noisetex  = texture/stbn.bin TEXTURE_3D RGB8 128 128 64 RGB UNSIGNED_BYTE
texture.prepare.noisetex   = texture/stbn.bin TEXTURE_3D RGB8 128 128 64 RGB UNSIGNED_BYTE
texture.begin.noisetex     = texture/stbn.bin TEXTURE_3D RGB8 128 128 64 RGB UNSIGNED_BYTE

texture.composite.depthtex2 = texture/tonyMcMapface.bin TEXTURE_3D RGBA32F 48 48 48 RGBA FLOAT

#------# Custom Uniforms #----------------------#

variable.float.cameraVelocity_x = floor(cameraPositionInt.x - previousCameraPositionInt.x) + (cameraPositionFract.x - previousCameraPositionFract.x)
variable.float.cameraVelocity_y = floor(cameraPositionInt.y - previousCameraPositionInt.y) + (cameraPositionFract.y - previousCameraPositionFract.y)
variable.float.cameraVelocity_z = floor(cameraPositionInt.z - previousCameraPositionInt.z) + (cameraPositionFract.z - previousCameraPositionFract.z)

uniform.vec3.cameraVelocity = vec3(cameraVelocity_x, cameraVelocity_y, cameraVelocity_z)

variable.float.sunDir_x = gbufferModelViewInverse.0.0 * sunPosition.x + gbufferModelViewInverse.1.0 * sunPosition.y + gbufferModelViewInverse.2.0 * sunPosition.z
variable.float.sunDir_y = gbufferModelViewInverse.0.1 * sunPosition.x + gbufferModelViewInverse.1.1 * sunPosition.y + gbufferModelViewInverse.2.1 * sunPosition.z
variable.float.sunDir_z = gbufferModelViewInverse.0.2 * sunPosition.x + gbufferModelViewInverse.1.2 * sunPosition.y + gbufferModelViewInverse.2.2 * sunPosition.z
variable.float.sunDirNorm = 1.0 / sqrt((sunDir_x * sunDir_x) + (sunDir_y * sunDir_y) + (sunDir_z * sunDir_z))

variable.float.sunDirNorm_x = sunDir_x * sunDirNorm
variable.float.sunDirNorm_y = sunDir_y * sunDirNorm
variable.float.sunDirNorm_z = sunDir_z * sunDirNorm

variable.float.moonDir_x = gbufferModelViewInverse.0.0 * moonPosition.x + gbufferModelViewInverse.1.0 * moonPosition.y + gbufferModelViewInverse.2.0 * moonPosition.z
variable.float.moonDir_y = gbufferModelViewInverse.0.1 * moonPosition.x + gbufferModelViewInverse.1.1 * moonPosition.y + gbufferModelViewInverse.2.1 * moonPosition.z
variable.float.moonDir_z = gbufferModelViewInverse.0.2 * moonPosition.x + gbufferModelViewInverse.1.2 * moonPosition.y + gbufferModelViewInverse.2.2 * moonPosition.z
variable.float.moonDirNorm = 1.0 / sqrt((moonDir_x * moonDir_x) + (moonDir_y * moonDir_y) + (moonDir_z * moonDir_z))

variable.float.moonDirNorm_x = moonDir_x * moonDirNorm
variable.float.moonDirNorm_y = moonDir_y * moonDirNorm
variable.float.moonDirNorm_z = moonDir_z * moonDirNorm

uniform.vec3.shadowDir = vec3(if(sunAngle == shadowAngle, sunDirNorm_x, moonDirNorm_x), if(sunAngle == shadowAngle, sunDirNorm_y, moonDirNorm_y), if(sunAngle == shadowAngle, sunDirNorm_z, moonDirNorm_z))
uniform.vec3.moonDir = vec3(moonDirNorm_x, moonDirNorm_y, moonDirNorm_z)
uniform.vec3.sunDir = vec3(sunDirNorm_x, sunDirNorm_y, sunDirNorm_z)

#ifdef VOXY
    variable.float.lodNear = near
    variable.float.lodFar = 32.0 * vxRenderDistance
#else
    variable.float.lodNear = near
    variable.float.lodFar = far
#endif

uniform.vec4.lodProjMat_0 = vec4(gbufferProjection.0.0, gbufferProjection.0.1, 0.0, 0.0)
uniform.vec4.lodProjMat_1 = vec4(gbufferProjection.1.0, gbufferProjection.1.1, 0.0, 0.0)
uniform.vec4.lodProjMat_2 = vec4(0.0, 0.0, -2.0 * lodNear / (lodFar - lodNear), -1.0)
uniform.vec4.lodProjMat_3 = vec4(0.0, 0.0, -2.0 * lodFar * lodNear / (lodFar - lodNear), 0.0)

uniform.vec4.lodProjMatPrev_0 = vec4(gbufferPreviousProjection.0.0, gbufferPreviousProjection.0.1, 0.0, 0.0)
uniform.vec4.lodProjMatPrev_1 = vec4(gbufferPreviousProjection.1.0, gbufferPreviousProjection.1.1, 0.0, 0.0)
uniform.vec4.lodProjMatPrev_2 = vec4(0.0, 0.0, -2.0 * lodNear / (lodFar - lodNear), -1.0)
uniform.vec4.lodProjMatPrev_3 = vec4(0.0, 0.0, -2.0 * (lodFar * lodNear) / (lodFar - lodNear), 0.0)

uniform.vec4.lodProjMatInv_0 = vec4(gbufferProjectionInverse.0.0, gbufferProjectionInverse.0.1, 0.0, 0.0)
uniform.vec4.lodProjMatInv_1 = vec4(gbufferProjectionInverse.1.0, gbufferProjectionInverse.1.1, 0.0, 0.0)
uniform.vec4.lodProjMatInv_2 = vec4(0.0, 0.0, 0.0, (lodNear - lodFar) / (2.0 * lodNear * lodFar))
uniform.vec4.lodProjMatInv_3 = vec4(0.0, 0.0, -1.0, 1.0 / lodFar)

variable.float.renderScale          = 0.01 * TEMPORAL_UPSAMPLING

uniform.vec2.screenSize             = vec2(viewWidth, viewHeight)
uniform.vec2.texelSize              = vec2(1.0 / viewWidth, 1.0 / viewHeight)

variable.float.internalScreenSize_x = renderScale * viewWidth
variable.float.internalScreenSize_y = renderScale * viewHeight

uniform.vec2.internalScreenSize     = vec2(internalScreenSize_x, internalScreenSize_y)

variable.float.internalTexelSize_x  = 1.0 / internalScreenSize_x
variable.float.internalTexelSize_y  = 1.0 / internalScreenSize_y

uniform.vec2.internalTexelSize      = vec2(internalTexelSize_x, internalTexelSize_y)

variable.float.offsetIndex = floor(0.5 * (frameCounter % 16) + 1.0)
variable.float.offsetIndexPrev = floor(0.5 * ((frameCounter - 1) % 16) + 1.0)

variable.bool.inverse = frameCounter % 2 == 0

variable.float.taa_offset_x = if(inverse, -TAA_JITTER_SCALE, TAA_JITTER_SCALE) * internalTexelSize_x * (frac(1.3247179 * offsetIndex + 0.5) * 2.0 - 1.0)
variable.float.taa_offset_y = if(inverse, -TAA_JITTER_SCALE, TAA_JITTER_SCALE) * internalTexelSize_y * (frac(1.7548776 * offsetIndex + 0.5) * 2.0 - 1.0)

uniform.vec2.taa_offset = vec2(taa_offset_x, taa_offset_y)

variable.float.taa_offset_prev_x = if(inverse, TAA_JITTER_SCALE, -TAA_JITTER_SCALE) * internalTexelSize_x * (frac(1.3247179 * offsetIndexPrev + 0.5) * 2.0 - 1.0)
variable.float.taa_offset_prev_y = if(inverse, TAA_JITTER_SCALE, -TAA_JITTER_SCALE) * internalTexelSize_y * (frac(1.7548776 * offsetIndexPrev + 0.5) * 2.0 - 1.0)

uniform.vec2.taa_offset_prev = vec2(taa_offset_prev_x, taa_offset_prev_y)