oldLighting = false

#if TEMPORAL_UPSAMPLING == 100
    size.buffer.colortex7 = 1.0 1.0
#elif TEMPORAL_UPSAMPLING == 83
    size.buffer.colortex7 = 0.83 0.83
#elif TEMPORAL_UPSAMPLING == 75
    size.buffer.colortex7 = 0.75 0.75
#elif TEMPORAL_UPSAMPLING == 66
    size.buffer.colortex7 = 0.66 0.66
#elif TEMPORAL_UPSAMPLING == 50
    size.buffer.colortex7 = 0.5 0.5
#elif TEMPORAL_UPSAMPLING == 33
    size.buffer.colortex7 = 0.33 0.33
#elif TEMPORAL_UPSAMPLING == 25
    size.buffer.colortex7 = 0.25 0.25
#endif

# https://discordapp.com/channels/237199950235041794/525510804494221312/1416364500591837216

texture.composite.noisetex = texture/stbn.bin TEXTURE_3D RGB8 128 128 64 RGB UNSIGNED_BYTE
texture.deferred.noisetex  = texture/stbn.bin TEXTURE_3D RGB8 128 128 64 RGB UNSIGNED_BYTE
texture.prepare.noisetex   = texture/stbn.bin TEXTURE_3D RGB8 128 128 64 RGB UNSIGNED_BYTE
texture.begin.noisetex     = texture/stbn.bin TEXTURE_3D RGB8 128 128 64 RGB UNSIGNED_BYTE

variable.float.cameraVelocity_x = floor(cameraPositionInt.x - previousCameraPositionInt.x) + (cameraPositionFract.x - previousCameraPositionFract.x)
variable.float.cameraVelocity_y = floor(cameraPositionInt.y - previousCameraPositionInt.y) + (cameraPositionFract.y - previousCameraPositionFract.y)
variable.float.cameraVelocity_z = floor(cameraPositionInt.z - previousCameraPositionInt.z) + (cameraPositionFract.z - previousCameraPositionFract.z)

uniform.vec3.cameraVelocity = vec3(cameraVelocity_x, cameraVelocity_y, cameraVelocity_z)

variable.float.renderScale          = 0.01 * TEMPORAL_UPSAMPLING

uniform.vec2.screenSize             = vec2(viewWidth, viewHeight)
uniform.vec2.texelSize              = vec2(1.0 / viewWidth, 1.0 / viewHeight)

variable.float.internalScreenSize_x = renderScale * viewWidth
variable.float.internalScreenSize_y = renderScale * viewHeight

uniform.vec2.internalScreenSize     = vec2(internalScreenSize_x, internalScreenSize_y)

variable.float.internalTexelSize_x  = 1.0 / internalScreenSize_x
variable.float.internalTexelSize_y  = 1.0 / internalScreenSize_y

uniform.vec2.internalTexelSize      = vec2(internalTexelSize_x, internalTexelSize_y)

#ifdef TAA
    variable.float.offsetIndex = floor(0.5 * (frameCounter % 16) + 1.0)
    variable.float.offsetIndexPrev = floor(0.5 * ((frameCounter - 1) % 16) + 1.0)

    variable.bool.inverse = frameCounter % 2 == 0

    variable.float.taa_offset_x = if(inverse, -TAA_JITTER_SCALE, TAA_JITTER_SCALE) * internalTexelSize_x * (frac(1.3247179 * offsetIndex + 0.5) * 2.0 - 1.0)
    variable.float.taa_offset_y = if(inverse, -TAA_JITTER_SCALE, TAA_JITTER_SCALE) * internalTexelSize_y * (frac(1.7548776 * offsetIndex + 0.5) * 2.0 - 1.0)

    uniform.vec2.taa_offset = vec2(taa_offset_x, taa_offset_y)

    variable.float.taa_offset_prev_x = if(inverse, TAA_JITTER_SCALE, -TAA_JITTER_SCALE) * internalTexelSize_x * (frac(1.3247179 * offsetIndexPrev + 0.5) * 2.0 - 1.0)
    variable.float.taa_offset_prev_y = if(inverse, TAA_JITTER_SCALE, -TAA_JITTER_SCALE) * internalTexelSize_y * (frac(1.7548776 * offsetIndexPrev + 0.5) * 2.0 - 1.0)

    uniform.vec2.taa_offset_prev = vec2(taa_offset_prev_x, taa_offset_prev_y)
#else
    uniform.vec2.taa_offset = vec2(0.0, 0.0)
    uniform.vec2.taa_offset_prev = vec2(0.0, 0.0)
#endif